version: 2.2.0.{build}
install:
- appveyor DownloadFile http://download.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.26.msi
- msiexec /i gtk-sharp-2.12.26.msi /qn /norestart
build_script:
- set BASE=%APPVEYOR_BUILD_FOLDER%
- set BUILD_VERSION=000%APPVEYOR_BUILD_NUMBER%
- set BUILD_VERSION=2.2.0-build%BUILD_VERSION:~-4%
- echo Downloading XamMac.dll for build..
- mkdir %BASE%\BuildOutput\net40\Release
- mkdir %BASE%\BuildOutput\net45\Release
- appveyor DownloadFile %XAMMAC_LOCATION%/XamMac.dll -FileName %BASE%\BuildOutput\net40\Release\XamMac.dll
- copy %BASE%\BuildOutput\net40\Release\XamMac.dll %BASE%\BuildOutput\net45\Release\XamMac.dll
- msbuild -t:Package -p:BuildVersion=%BUILD_VERSION% Resources\Build.targets /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /consoleloggerparameters:NoSummary
test: off
#test_script:
#- nunit-console --framework=4.0 --include=TestPlatform BuildOutput/net40/Release/test/Eto.Test.dll
#- nunit-console --framework=4.5 --include=TestPlatform BuildOutput/net45/Release/test/Eto.Test.dll
artifacts:
- path: BuildOutput/Nuget/Release/*.nupkg
  name: nuget
deploy:
- provider: Environment
  name: MyGet
  on:
    branch: develop